server:
    servlet:
        context-path: /api
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 30000
            minimum-idle: 10
            maximum-pool-size: 10
            idle-timeout: 600000
            max-lifetime: 1800000
            auto-commit: true
        jdbc-url: jdbc:postgresql://localhost/postgres
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update