spring:
    # autoconfigure:
    #     exclude:
    #         - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    #         - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    #         - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/native_image_demo_db
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                database-platform: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: create
